package com.example.util

data class AppStrings(
    val appName: String,
    val homeFeed: String,
    val sources: String,
    val tvNews: String,
    val favorites: String,
    val settings: String,
    val search: String,
    val searchPlaceholder: String,
    val searchSourcesPlaceholder: String,
    val latestNews: String,
    val breakingNews: String,
    val topNews: String,
    val seeAll: String,
    val clear: String,
    val readArticle: String,
    val savedOffline: String,
    val saveForOffline: String,
    val share: String,
    val notifications: String,
    val notificationDesc: String,
    val testAlert: String,
    val clearCache: String,
    val clearCacheDesc: String,
    val language: String,
    val languageDesc: String,
    val theme: String,
    val about: String,
    val privacyPolicy: String,
    val terms: String,
    val contactUs: String,
    val exitApp: String,
    val rateUs: String,
    val rateUsPrompt: String,
    val sendFeedback: String,
    val noArticlesFound: String,
    val noNewspapersFound: String,
    val openLiveSite: String,
    val allRegions: String,
    val allRadio: String,
    val browseCategories: String,
    val close: String,
    val done: String,
    val cancel: String
) {
    companion object {
        val English = AppStrings(
            appName = "NewsHub BD",
            homeFeed = "Home Feed",
            sources = "Sources",
            tvNews = "TV News",
            favorites = "Favorites",
            settings = "Settings",
            search = "Search",
            searchPlaceholder = "Search news or newspapers...",
            searchSourcesPlaceholder = "Search 400+ newspapers, jobs, radio, ministries...",
            latestNews = "Latest News",
            breakingNews = "Breaking News",
            topNews = "Top Headlines",
            seeAll = "See All",
            clear = "Clear",
            readArticle = "Read Article",
            savedOffline = "Article saved for offline reading 📥",
            saveForOffline = "Save for Offline",
            share = "Share",
            notifications = "Notifications",
            notificationDesc = "Breaking news alert notifications",
            testAlert = "Send Test Alert",
            clearCache = "Clear Offline Cache",
            clearCacheDesc = "Free up device storage & reset news cache",
            language = "Language",
            languageDesc = "English / বাংলা",
            theme = "Theme",
            about = "About",
            privacyPolicy = "Privacy Policy",
            terms = "Terms & Conditions",
            contactUs = "Contact Us",
            exitApp = "Exit App",
            rateUs = "Rate Us",
            rateUsPrompt = "How was your experience with NewsHub BD?",
            sendFeedback = "Send Feedback",
            noArticlesFound = "No news articles found",
            noNewspapersFound = "No newspapers or portals found",
            openLiveSite = "Open In-App Web",
            allRegions = "All Regions",
            allRadio = "All Radio",
            browseCategories = "BROWSE CATEGORIES",
            close = "Close",
            done = "Done",
            cancel = "Cancel"
        )

        val Bangla = AppStrings(
            appName = "নিউজহাব বিডি",
            homeFeed = "হোম ফিড",
            sources = "পত্রিকা ও সাইট",
            tvNews = "টিভি নিউজ",
            favorites = "সংরক্ষিত",
            settings = "সেটিংস",
            search = "অনুসন্ধান",
            searchPlaceholder = "সংবাদ বা পত্রিকা খুঁজুন...",
            searchSourcesPlaceholder = "৪০০+ পত্রিকা, চাকরি, রেডিও ও মন্ত্রণালয় খুঁজুন...",
            latestNews = "সর্বশেষ সংবাদ",
            breakingNews = "ব্রেকিং নিউজ",
            topNews = "শীর্ষ সংবাদ",
            seeAll = "সব দেখুন",
            clear = "মুছুন",
            readArticle = "বিস্তারিত পড়ুন",
            savedOffline = "খবরটি অফলাইনে পড়ার জন্য সংরক্ষিত হয়েছে 📥",
            saveForOffline = "অফলাইনে সংরক্ষণ",
            share = "শেয়ার",
            notifications = "নোটিফিকেশন",
            notificationDesc = "জরুরি ব্রেকিং নিউজ নোটিফিকেশন",
            testAlert = "টেস্ট নোটিফিকেশন পাঠান",
            clearCache = "অফলাইন ক্যাশ মুছুন",
            clearCacheDesc = "মেমোরি খালি করুন এবং নতুন সংবাদ লোড করুন",
            language = "ভাষা নির্বাচন",
            languageDesc = "বাংলা / English",
            theme = "থিম মোড",
            about = "অ্যাপ সম্পর্কে",
            privacyPolicy = "গোপনীয়তা নীতি",
            terms = "ব্যবহারের শর্তাবলী",
            contactUs = "যোগাযোগ করুন",
            exitApp = "অ্যাপ বন্ধ করুন",
            rateUs = "রেটিং দিন",
            rateUsPrompt = "নিউজহাব বিডি ব্যবহার করে আপনার কেমন লেগেছে?",
            sendFeedback = "মতামত পাঠান",
            noArticlesFound = "কোনো সংবাদ খুঁজে পাওয়া যায়নি",
            noNewspapersFound = "কোনো পত্রিকা বা পোর্টাল খুঁজে পাওয়া যায়নি",
            openLiveSite = "ইন-অ্যাপ ওয়েব ওপেন করুন",
            allRegions = "সব অঞ্চল",
            allRadio = "সব রেডিও",
            browseCategories = "ক্যাটাগরি সমূহ",
            close = "বন্ধ করুন",
            done = "সম্পন্ন",
            cancel = "বাতিল"
        )

        fun forLanguage(lang: String): AppStrings {
            return if (lang.contains("বাংলা") || lang.equals("Bangla", ignoreCase = true) || lang.equals("bn", ignoreCase = true)) {
                Bangla
            } else {
                English
            }
        }
    }
}
